name: tidbits
favicon: null
layout_spectrum: 0.9053527677897364
typography_spectrum: 0.4770435863174498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19954264676198363
  lightness: 0.82274623750709
  saturation: 0.032704082084819674
  rhythmicContrast: 0.7998796701431274
purpose: []
